### ISSUE TITLE
It works well, only one little mistake 

### ISSUE THREAD

**Issue by rtufino** [hassanyf/Simple-Server-and-Chat-Program#3]
Hi, your code it's a good work. I believe that you have a little mistake in server.cpp on line 224
`*buffer == '*';` the correct is `*buffer = '*';`

**Comment by M-I-R** [comment]
it s not working well ,actually it s not working at all :)

i wasted time looking for erros ,but the entire condiotion branchs and structures are not done correctly ,in my case the server and client doesn t see each other (or they do but because of "bad branch" structure there is a bad loop.

**Comment by hassanyousufx** [comment]
@M-I-R Kindly inform me what errors are you facing? This program was tested in Ubuntu 12.
